server:
  port: 8080
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ass2?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.msb.pojo
  mapper-locations: classpath:com/msb/mapper/*.xml
